#!/usr/bin/env bash

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

RETHINKDB_HOST="localhost"
RETHINKDB_PORT="28015"

rm -f .env

echo "RETHINKDB_HOST=$RETHINKDB_HOST" > .env
echo "RETHINKDB_PORT=$RETHINKDB_PORT" >> .env

pipenv install --python "$(command -v python3)"
