#!/usr/bin/env bash

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

script/update

test -z "$FLASK_APP" &&
  export FLASK_APP="tldb"

test -z "$FLASK_ENV" &&
  export FLASK_ENV="development"

# ensure rethinkdb is running as a daemon
if [[ -z $(ps -eo 'tty,pid,comm' | grep ^? | grep rethinkdb) ]]; then
  rethinkdb --daemon --http-port 8081
fi

pipenv run python3 ./script/update_database.py

pipenv run flask run
