#!/usr/bin/env bash

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

script/update

test -z "$FLASK_APP" &&
  export FLASK_APP="tldb"

test -z "$FLASK_ENV" &&
  export FLASK_ENV="development"

pipenv run flask run
