#!/usr/bin/env bash

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

if [[ ! -z $(command -v pre-commit) ]]; then
    echo "Installing pre-commit hooks..."

    pre-commit install
fi
