#!/usr/bin/env bash

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

if [[ ! -z $(command -v pre-commit) ]]; then
    echo "Installing pre-commit hooks..."

    pre-commit install
fi

if [[ -z $(command -v rethinkdb) ]]; then
    source /etc/lsb-release && echo "deb https://download.rethinkdb.com/repository/ubuntu-$DISTRIB_CODENAME $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
    wget -qO- https://download.rethinkdb.com/repository/raw/pubkey.gpg | sudo apt-key add -
    sudo apt update
    sudo apt install -y rethinkdb
fi
